import { Link } from 'react-router-dom';

export default function Page01OverviewProblemStatement() {
  return (
    <main className="flex-1 min-w-0 overflow-y-auto  p-6 md:p-12 relative">
      <div>
  <nav className="text-sm text-gray-500 dark:text-gray-400 mb-8">
    <a href="#" className="hover:underline">Home</a> /
    <a href="#" className="hover:underline">Overview</a> /
    <span className="font-medium text-gray-900 dark:text-gray-200">Problem Statement</span>
  </nav>
  <article className="markdown-body max-w-3xl">
    <h1>Problem Statement</h1>
    <h2 id="context">Context</h2>
    <p>Sound, as we commonly experience it, consists of pressure waves oscillating at frequencies the
      human ear can detect — roughly 20 Hz to 20,000 Hz. Below this audible range lies
      <strong>infrasound</strong>: atmospheric pressure waves that oscillate at extremely low
      frequencies, approximately <strong>0.01 Hz to 20 Hz</strong>.
    </p>
    <blockquote>
      <p><strong>Simple Analogy:</strong>
        A normal microphone is like a fast camera — it captures rapid vibrations in air. An
        infrasound sensor is like a time-lapse camera — it captures extremely slow atmospheric
        pressure changes that happen over seconds or even minutes.</p>
    </blockquote>
    <p>These very-low-frequency pressure waves are generated by powerful natural and human-made events:
    </p>
    <ul>
      <li>Volcanic eruptions</li>
      <li>Large meteorological disturbances (severe storms, hurricanes)</li>
      <li>Meteor entries into the atmosphere</li>
      <li>Large explosions</li>
      <li>Rocket launches</li>
      <li>Ocean wave interactions (microbaroms)</li>
    </ul>
    <p>Infrasound waves can travel hundreds or even thousands of kilometres through the atmosphere
      because low-frequency waves experience less atmospheric absorption than audible sound. This
      makes infrasound monitoring valuable for detecting distant events that are impossible to hear.
    </p>
    <h2 id="the-problem">The Problem</h2>
    <h3 id="1-detection-is-technically-difficult">1. Detection Is Technically Difficult</h3>
    <p>At 0.01 Hz, a single pressure oscillation takes <strong>100 seconds</strong> to complete. The
      pressure variations involved can be extremely small — often fractions of a Pascal against a
      background atmospheric pressure of approximately 101,325 Pa. Detecting a signal that is many
      orders of magnitude smaller than the background, and that changes over timescales of seconds to
      minutes, is fundamentally harder than detecting audible sound.</p>
    <h3 id="2-normal-microphones-are-insufficient">2. Normal Microphones Are Insufficient</h3>
    <p>Standard microphones are designed for the audible frequency range (20 Hz – 20 kHz). They
      typically:</p>
    <ul>
      <li>Have a high-pass frequency response that rolls off below ~20 Hz</li>
      <li>Are not designed for the sensitivity and stability needed at sub-hertz frequencies</li>
      <li>Lack the DC-coupled or quasi-DC signal path required for very slow pressure changes</li>
      <li>Do not include mechanisms to suppress slow barometric drift</li>
    </ul>
    <h3 id="3-wind-noise-dominates">3. Wind Noise Dominates</h3>
    <p>Wind flowing over a sensor port creates turbulent pressure fluctuations. These fluctuations can
      be orders of magnitude larger than the infrasound signal of interest, especially at frequencies
      below a few hertz. Without dedicated wind-noise reduction, the signal is buried in environmental
      noise.</p>
    <h3 id="4-temperature-and-barometric-drift">4. Temperature and Barometric Drift</h3>
    <p>Over minutes and hours, atmospheric pressure changes due to weather patterns, diurnal heating,
      and altitude variations. Temperature changes also affect sensor electronics and mechanical
      components. These slow drifts must be suppressed or compensated, otherwise they overwhelm the
      infrasound measurement.</p>
    <h3 id="5-existing-systems-are-complex-and-expensive">5. Existing Systems Are Complex and Expensive
    </h3>
    <p>Professional infrasound monitoring systems — such as those operated by the Comprehensive
      Nuclear-Test-Ban Treaty Organization (CTBTO) International Monitoring System (IMS) — use
      research-grade microbarometers, large spatial-filtering pipe arrays (sometimes spanning 1–3 km),
      and sophisticated data processing infrastructure. These are designed for treaty verification and
      scientific research, making them inaccessible for educational and small-scale applications.</p>
    <h2 id="proposed-problem-statement">Proposed Problem Statement</h2>
    <blockquote>
      <p><strong>There is a need for a practical, low-cost prototype system capable of:</strong></p>
      <ol>
        <li><strong>Detecting atmospheric pressure variations</strong> in the 0.01–20 Hz (TARGET - Pending experimental validation) frequency
          range</li>
        <li><strong>Reducing wind and environmental noise</strong> using a spatial-averaging
          manifold</li>
        <li><strong>Suppressing slow barometric drift</strong> through differential-pressure design
          with a reference chamber</li>
        <li><strong>Digitizing the signal</strong> with sufficient resolution and sampling rate</li>
        <li><strong>Processing the digital signal</strong> using filtering, FFT, and spectral
          analysis</li>
        <li><strong>Extracting meaningful features</strong> from the processed signal</li>
        <li><strong>Detecting anomalous patterns</strong> using AI-based anomaly detection</li>
        <li><strong>Visualizing results</strong> on a real-time dashboard with alerting</li>
      </ol>
      <p>The system should be accessible enough for student teams and hackathon projects while being
        technically sound enough for educational research and atmospheric monitoring exploration.
      </p>
    </blockquote>
    <h2 id="what-this-problem-statement-does-not-claim">What This Problem Statement Does NOT Claim</h2>
    <ul>
      <li>It does NOT claim the system will replace professional-grade infrasound networks</li>
      <li>It does NOT guarantee detection of specific event types (explosions, meteors, etc.)</li>
      <li>It does NOT claim the AI will classify events — the MVP focuses on anomaly detection</li>
      <li>It does NOT assume the prototype will achieve professional noise-floor specifications</li>
    </ul>
    <h2 id="success-criteria">Success Criteria</h2>
    <p>The prototype successfully addresses this problem statement if it can demonstrate:</p>
    <ol>
      <li>Measurable response to controlled low-frequency pressure variations</li>
      <li>Visible reduction in noise when wind-noise reduction is engaged</li>
      <li>Clean digitized waveform display</li>
      <li>Correct FFT/spectral analysis output</li>
      <li>AI anomaly detection flagging controlled test signals as anomalous</li>
      <li>Dashboard displaying real-time data and alerts</li>
    </ol>
    <hr />
    <p><em>See also: <Link to="/01-overview/project-objectives">Project Objectives</Link> | <Link to="/01-overview/proposed-solution">Proposed Solution</Link> | <Link to="/01-overview/scope-and-limitations">Scope and Limitations</Link></em></p>
  </article>
</div>

    </main>
  );
}